/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testes;

/**
 *
 * @author lordt
 */
public class Calc extends javax.swing.JFrame {
    
    //aqui declarei as variaveis x e y
    public static int x, y;

    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // todos os codigos ja montados não devem ser alterados 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n1txt = new javax.swing.JTextField();
        n2txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rstxt = new javax.swing.JTextField();
        sumBt = new javax.swing.JButton();
        subBt = new javax.swing.JButton();
        divBt = new javax.swing.JButton();
        mtlBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Número 1:");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel2.setText("Número 2:");

        n1txt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        n1txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        n1txt.setText("0");
        n1txt.setAutoscrolls(false);
        n1txt.setMinimumSize(new java.awt.Dimension(100, 20));

        n2txt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        n2txt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        n2txt.setText("0");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jLabel3.setText("Resultado:");

        rstxt.setEditable(false);
        rstxt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        rstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rstxt.setText("0");

        sumBt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        sumBt.setText("Soma");
        sumBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sumBtMouseReleased(evt);
            }
        });

        subBt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        subBt.setText("Subtração");
        subBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                subBtMouseReleased(evt);
            }
        });

        divBt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        divBt.setText("Divisão");
        divBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                divBtMouseReleased(evt);
            }
        });

        mtlBt.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        mtlBt.setText("Multiplicação");
        mtlBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mtlBtMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(n1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(n2txt)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rstxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sumBt)
                .addGap(18, 18, 18)
                .addComponent(subBt)
                .addGap(18, 18, 18)
                .addComponent(divBt)
                .addGap(18, 18, 18)
                .addComponent(mtlBt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rstxt))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(n1txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(n2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumBt)
                    .addComponent(subBt)
                    .addComponent(divBt)
                    .addComponent(mtlBt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtMouseReleased
        //aqui iremos adicionar nossas variaveis
        try
        {
            x = Integer.parseInt( n1txt.getText());
            y = Integer.parseInt( n2txt.getText());
            rstxt.setText((x-y)+"");
        }
        catch(NumberFormatException num)
        {
            x = 0;
            y = 0;
            rstxt.setText("?"); 
        }   
    }//GEN-LAST:event_subBtMouseReleased

    private void sumBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumBtMouseReleased
       int x, y;
        x = Integer.parseInt( n1txt.getText());
        y = Integer.parseInt( n2txt.getText());
        rstxt.setText((x+y)+"");
    }//GEN-LAST:event_sumBtMouseReleased

    private void divBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divBtMouseReleased
        int x, y;
        x = Integer.parseInt( n1txt.getText());
        y = Integer.parseInt( n2txt.getText());
        rstxt.setText((x/y)+"");
    }//GEN-LAST:event_divBtMouseReleased

    private void mtlBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtlBtMouseReleased
        int x, y;
        x = Integer.parseInt( n1txt.getText());
        y = Integer.parseInt( n2txt.getText());
        rstxt.setText((x*y)+"");
    }//GEN-LAST:event_mtlBtMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mtlBt;
    private javax.swing.JTextField n1txt;
    private javax.swing.JTextField n2txt;
    private javax.swing.JTextField rstxt;
    private javax.swing.JButton subBt;
    private javax.swing.JButton sumBt;
    // End of variables declaration//GEN-END:variables
}
